name: Demo

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  demo:
    runs-on: macos-latest
    steps:
    - name: Setup python environment
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: env
        condarc: |
              channels:
                - conda-forge
        create-args: >-
          python=3.11
          packaging
          scipy
          pyinstaller
        init-shell: bash

    - name: list environment
      shell: bash -l {0}
      run: micromamba list

    - uses: actions/checkout@v3

    - name: Run from conda-env
      shell: bash -l {0}
      run: python repro.py

    - name: Build binaries
      shell: bash -l {0}
      run: pyinstaller repro.py

    - name: Run binaries
      shell: bash -l {0}
      run: ./dist/repro/repro
